# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
format = 'on [$symbol($profile)(\($region\) )]($style)'
style = 'blue italic'
symbol = '⛅︎'
[aws.region_aliases]
eu-central-1 = "euc1"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"

[cmd_duration]
min_time = 15_000
style = "italic yellow"

[directory]
style = "blue"
truncation_length = 5
truncate_to_repo = true

[docker_context]
disabled = true

[env_var]
variable = "AWSUME_PROFILE"
symbol = ""
style = "italic yellow"

[git_branch]
format = "on [$branch]($style) "
style = "bright-black italic"
truncation_symbol = "…"

[git_state]
style = "italic yellow"

[git_status]
style = "bright-black"
stashed = ""

[hostname]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true

[terraform]
disabled = true

[custom.tfenv]
command = "tfenv version-name"
extensions = ["tf", "tfplan", "tfstate"]
style = "green"
format = "tf [$output]($style)"
disabled = true

[username]
disabled = true

[gcloud]
disabled = true

[ruby]
disabled = true

[kubernetes]
disabled = false
